name:          SQL Server style guide by Wesley Brown
description:   A consistent code style guide for SQL specific to SQL Server to ensure legible and maintainable projects

url:           https://sqlserverio.github.io/sqlstyle.guide/
domain:        sqlserverio.github.io
port:          4040

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: "2,3"
