name:          SQL Style Guide by Simon Holywell
description:   A consistent SQL style guide for greater readability and easier maintenance.
url:           http://www.sqlstyle.guide

markdown:      rdiscount
permalink:     pretty
highlighter:   pygments
